# This is a basic workflow to help you get started with Actions

name: Deploy DongTai Engine To TEST

on:
  pull_request:
    branches: [ "dev-*" ]
  push:
    branches: [ "dev-*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy To Dev:
    # The type of runner that the job will run on
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: start-build
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：项目${{github.repository}}构建开始\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: 3.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.ALIYUN_REGISTRY}}
          username: ${{secrets.ALIYUN_DOCKERHUB_USER}}
          password: ${{secrets.ALIYUN_DOCKERHUB_PASSWORD}}
          logout: true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: DockerfileTest
          push: true
          tags: "registry.cn-beijing.aliyuncs.com/secnium/iast-saas-engine-dev:0.1.${{github.run_number}},registry.cn-beijing.aliyuncs.com/secnium/iast-saas-engine-dev:latest"

      - name: deploy Engine to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DEV_DATA }}
        with:
          args: |
            find deploy/deploy-eks-iast-saas-engine-dev.yml -type f -exec sed -i 's/VERSION/0.1.${{github.run_number}}/g' {} \;
            ls deploy/deploy-eks-iast-saas-engine-dev.yml | xargs -I {} kubectl apply -f {}

      - name: deploy Engine Task to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DEV_DATA }}
        with:
          args: |
            find deploy/deploy-eks-iast-saas-engine-task-dev.yml -type f -exec sed -i 's/VERSION/0.1.${{github.run_number}}/g' {} \;
            ls deploy/deploy-eks-iast-saas-engine-task-dev.yml | xargs -I {} kubectl apply -f {}

      - name: finish build
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "状态：项目${{github.repository}}构建成功\n分支：${{github.ref}}\n流程：${{github.workflow}}\n构建编号：${{github.run_number}}\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}\nSHA-1：${{github.sha}}\n","tag": "lark_md"}}]}}'
