# This is a basic workflow to help you get started with Actions

name: Deploy DongTai Engine To AWS Test

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: 3.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Django Testing project
        run: |
          cp conf/config.ini.example conf/config.ini
          python3 manage.py migrate
          python3 manage.py test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.ALIYUN_REGISTRY}} 
          username: ${{secrets.ALIYUN_DOCKERHUB_USER}} 
          password: ${{secrets.ALIYUN_DOCKERHUB_PASSWORD}}
          logout: true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: DockerfileTest
          push: true
          tags: "registry.cn-beijing.aliyuncs.com/secnium/iast-saas-engine-test:latest,registry.cn-beijing.aliyuncs.com/secnium/iast-saas-engine-test:0.1.${{github.run_number}},"

      - name: deploy Engine to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST_DATA }}
        with:
          args: |
            find deploy/deploy-eks-iast-saas-engine-test.yml -type f -exec sed -i 's/VERSION/0.1.${{github.run_number}}/g' {} \;
            ls deploy/deploy-eks-iast-saas-engine-test.yml | xargs -I {} kubectl apply -f {}
            
      - name: deploy Engine Task to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST_DATA }}
        with:
          args: |
            find deploy/deploy-eks-iast-saas-engine-task-test.yml -type f -exec sed -i 's/VERSION/0.1.${{github.run_number}}/g' {} \;
            ls deploy/deploy-eks-iast-saas-engine-task-test.yml | xargs -I {} kubectl apply -f {}
